const flashcards = [
    { kanji: 'プログラミング', meaning: 'Lập trình' },
    { kanji: 'プログラマー', meaning: 'Lập trình viên  / dev / developer' },
    { kanji: 'コード', meaning: 'Mã' },
    { kanji: 'プログラミング言語 ', meaning: 'Ngôn ngữ lập trình' },
    { kanji: '変数', meaning: 'Biến' },
    { kanji: '関数 ', meaning: 'Hàm' },
    { kanji: '条件', meaning: 'Điều kiện' },
    { kanji: 'ループ', meaning: 'Vòng lặp' },
    { kanji: 'オブジェクト指向 ', meaning: 'Lập trình hướng đối tượng' },
    { kanji: 'オペレーティングシステム', meaning: 'Hệ điều hành' },
    { kanji: 'アプリケーション ', meaning: 'Ứng dụng' },
    { kanji: 'ウェブブラウザ', meaning: 'Trình duyệt web' },
    { kanji: 'オフィススイート', meaning: 'Bộ ứng dụng văn phòng' },
    { kanji: 'セキュリティソフト', meaning: 'Phần mềm bảo mật' },
    { kanji: 'ゲームソフト ', meaning: 'Phần mềm trò chơi' },
    { kanji: 'グラフィックソフト', meaning: 'Phần mềm đồ họa in' },
    { kanji: '動画編集ソフト', meaning: 'Phần mềm chỉnh sửa video' },
    { kanji: '音楽編集ソフト', meaning: 'Phần mềm chỉnh sửa âm nhạc' },
    { kanji: 'ネットワーク ', meaning: 'Mạng' },
    { kanji: 'インターネット ', meaning: 'Internet' },
    { kanji: 'ウェブサイト ', meaning: 'Trang web' },
    { kanji: 'メール', meaning: 'Email' },
    { kanji: 'サーバー', meaning: 'Máy chủ' },
    { kanji: 'ルーター', meaning: 'Router' },
    { kanji: 'モデム ', meaning: 'Modem' },
    { kanji: '無線LAN', meaning: 'Mạng LAN không dây' },
    { kanji: 'VPN', meaning: 'Mạng riêng ảo' },
    { kanji: 'プログラミング', meaning: 'Lập trình' },
    { kanji: 'プログラマー', meaning: 'Lập trình viên  / dev / developer' },
    { kanji: 'コード', meaning: 'Mã' },
    { kanji: 'プログラミング言語 ', meaning: 'Ngôn ngữ lập trình' },
    { kanji: '変数', meaning: 'Biến' },
    { kanji: '関数 ', meaning: 'Hàm' },
    { kanji: '条件', meaning: 'Điều kiện' },
    { kanji: 'ループ', meaning: 'Vòng lặp' },
    { kanji: 'オブジェクト指向 ', meaning: 'Lập trình hướng đối tượng' }
];