const flashcards1 = [	
	{ kanji: '概要', furigana: 'がいよう', meaning: 'Khái quát' } ,
	{ kanji: '資料', furigana: 'しりょう', meaning: 'Tài liệu' } ,
	{ kanji: '相談', furigana: 'そうだん', meaning: 'Trao đổi' } ,
	{ kanji: '順番', furigana: 'じゅんばん', meaning: 'Thứ tự' } ,
	{ kanji: 'デジタル', furigana: 'でじたる', meaning: 'Kỹ thuật (số)' } ,
	{ kanji: '映す', furigana: 'うつす', meaning: 'Phản ánh' } ,
	{ kanji: '体制', furigana: 'たいせい', meaning: 'Tổ chức (dự án)' } ,
	{ kanji: '開発手法', furigana: 'かいはつしゅほう', meaning: 'Phương thức phát triển' } ,
	{ kanji: '課題', furigana: 'かだい', meaning: 'Vấn đề' } ,
	{ kanji: '順を追う', furigana: 'じゅんをおう', meaning: 'Theo thứ tự, theo trình tự' } ,
	{ kanji: '既存', furigana: 'きぞん', meaning: 'Sẵn có, có sẵn' } ,
	{ kanji: '取入', furigana: 'とりいれ', meaning: 'Áp dụng, ứng dụng' } ,
	{ kanji: '機能', furigana: 'きのう', meaning: 'Chức năng, tính năng' } ,
	{ kanji: '拡張', furigana: 'かくちょう', meaning: 'Mở rộng (tính năng)' } ,
	{ kanji: '工数', furigana: 'こうすう', meaning: 'Effort, số công (làm việc)' } ,
];	
